import 'package:dnd_helper_flutter/models/arms_data/arms_data.dart';
import 'package:dnd_helper_flutter/models/coins_data/coins_data.dart';
import 'package:dnd_helper_flutter/models/enums/damage_types.dart';
import 'package:dnd_helper_flutter/models/enums/dice.dart';

class ArmsDataRepository {
  List<ArmsData> getAllSimpleWeapons() {
    return _allArms.where((arm) => arm.isSimple == true).toList();
  }

  List<ArmsData> getAllMartialWeapons() {
    return _allArms.where((arm) => arm.isSimple == false).toList();
  }

  List<ArmsData> getAllArms() {
    return _allArms;
  }

  static final List<ArmsData> _allArms = [
    const ArmsData(
        name: 'Club',
        isSimple: true,
        isMelee: true,
        price: CoinsData(silver: 1),
        damage: Dice.d4,
        damageType: DamageTypes.bludgeoning,
        weight: 2,
        armsFeatures: ["Light"],
        image: null),
    const ArmsData(
        name: 'Dagger',
        isSimple: true,
        isMelee: true,
        price: CoinsData(golden: 2),
        damage: Dice.d4,
        damageType: DamageTypes.piercing,
        weight: 1,
        armsFeatures: ["Finesse", "Light", "Thrown"],
        image: null),
    const ArmsData(
        name: 'Greatclub',
        isSimple: true,
        isMelee: true,
        price: CoinsData(silver: 2),
        damage: Dice.d8,
        damageType: DamageTypes.bludgeoning,
        weight: 10,
        armsFeatures: ["Two-handed"],
        image: null),
    const ArmsData(
        name: 'Handaxe',
        isSimple: true,
        isMelee: true,
        price: CoinsData(golden: 5),
        damage: Dice.d6,
        damageType: DamageTypes.slashing,
        weight: 2,
        armsFeatures: ["Light", "Thrown"],
        image: null),
    const ArmsData(
        name: 'Javelin',
        isSimple: true,
        isMelee: true,
        price: CoinsData(silver: 5),
        damage: Dice.d6,
        damageType: DamageTypes.piercing,
        weight: 2,
        armsFeatures: ["Thrown"],
        image: null),
    const ArmsData(
        name: 'Light hammer',
        isSimple: true,
        isMelee: true,
        price: CoinsData(silver: 2),
        damage: Dice.d4,
        damageType: DamageTypes.bludgeoning,
        weight: 2,
        armsFeatures: ["Light", "Thrown"],
        image: null),
    const ArmsData(
        name: 'Mace',
        isSimple: true,
        isMelee: true,
        price: CoinsData(golden: 5),
        damage: Dice.d6,
        damageType: DamageTypes.bludgeoning,
        weight: 4,
        armsFeatures: [],
        image: null),
    const ArmsData(
        name: 'Quarterstaff',
        isSimple: true,
        isMelee: true,
        price: CoinsData(silver: 2),
        damage: Dice.d6,
        damageType: DamageTypes.bludgeoning,
        weight: 4,
        armsFeatures: ["Versatile"],
        image: null),
    const ArmsData(
        name: 'Sickle',
        isSimple: true,
        isMelee: true,
        price: CoinsData(golden: 1),
        damage: Dice.d4,
        damageType: DamageTypes.slashing,
        weight: 2,
        armsFeatures: ["Light"],
        image: null),
    const ArmsData(
        name: 'Spear',
        isSimple: true,
        isMelee: true,
        price: CoinsData(golden: 1),
        damage: Dice.d6,
        damageType: DamageTypes.piercing,
        weight: 3,
        armsFeatures: ["Thrown", "Versatile"],
        image: null),
    const ArmsData(
        name: 'Crossbow, light',
        isSimple: true,
        isMelee: false,
        price: CoinsData(golden: 25),
        damage: Dice.d8,
        damageType: DamageTypes.piercing,
        weight: 5,
        armsFeatures: ["Ammunition", "Loading", "Two-handed"],
        image: null),
    const ArmsData(
        name: 'Dart',
        isSimple: true,
        isMelee: false,
        price: CoinsData(copper: 5),
        damage: Dice.d4,
        damageType: DamageTypes.piercing,
        weight: 0.25,
        armsFeatures: ["Finesse", "Thrown"],
        image: null),
    const ArmsData(
        name: 'Shortbow',
        isSimple: true,
        isMelee: false,
        price: CoinsData(golden: 25),
        damage: Dice.d6,
        damageType: DamageTypes.piercing,
        weight: 2,
        armsFeatures: ["Ammunition", "Two-handed"],
        image: null),
    const ArmsData(
        name: 'Sling',
        isSimple: true,
        isMelee: false,
        price: CoinsData(copper: 1),
        damage: Dice.d4,
        damageType: DamageTypes.bludgeoning,
        weight: 0,
        armsFeatures: ["Ammunition"],
        image: null),
    const ArmsData(
        name: 'Battleaxe',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 10),
        damage: Dice.d8,
        damageType: DamageTypes.slashing,
        weight: 4,
        armsFeatures: ["Versatile"],
        image: null),
    const ArmsData(
        name: 'Flail',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 10),
        damage: Dice.d8,
        damageType: DamageTypes.bludgeoning,
        weight: 2,
        armsFeatures: [],
        image: null),
    const ArmsData(
        name: 'Glaive',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 20),
        damage: Dice.d10,
        damageType: DamageTypes.slashing,
        weight: 6,
        armsFeatures: ["Heavy", "Reach", "Two-handed"],
        image: null),
    const ArmsData(
        name: 'Greataxe',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 30),
        damage: Dice.d12,
        damageType: DamageTypes.slashing,
        weight: 7,
        armsFeatures: ["Heavy", "Two-handed"],
        image: null),
    const ArmsData(
        name: 'Greatsword',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 50),
        damage: Dice.d6,
        damageType: DamageTypes.slashing,
        weight: 6,
        armsFeatures: ["Heavy", "Two-handed"],
        image: null),
    const ArmsData(
        name: 'Halberd',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 20),
        damage: Dice.d10,
        damageType: DamageTypes.slashing,
        weight: 6,
        armsFeatures: ["Heavy", "Reach", "Two-handed"],
        image: null),
    const ArmsData(
        name: 'Lance',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 10),
        damage: Dice.d12,
        damageType: DamageTypes.piercing,
        weight: 6,
        armsFeatures: ["Reach", "Special"],
        image: null),
    const ArmsData(
        name: 'Longsword',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 15),
        damage: Dice.d8,
        damageType: DamageTypes.slashing,
        weight: 3,
        armsFeatures: ["Versatile"],
        image: null),
    const ArmsData(
        name: 'Maul',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 10),
        damage: Dice.d6,
        damageType: DamageTypes.bludgeoning,
        weight: 10,
        armsFeatures: ["Heavy", "Two-handed"],
        image: null),
    const ArmsData(
        name: 'Morningstar',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 15),
        damage: Dice.d8,
        damageType: DamageTypes.piercing,
        weight: 4,
        armsFeatures: [],
        image: null),
    const ArmsData(
        name: 'Pike',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 5),
        damage: Dice.d10,
        damageType: DamageTypes.piercing,
        weight: 18,
        armsFeatures: ["Heavy", "Reach", "Two-handed"],
        image: null),
    const ArmsData(
        name: 'Rapier',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 25),
        damage: Dice.d8,
        damageType: DamageTypes.piercing,
        weight: 2,
        armsFeatures: ["Finesse"],
        image: null),
    const ArmsData(
        name: 'Scimitar',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 25),
        damage: Dice.d6,
        damageType: DamageTypes.slashing,
        weight: 3,
        armsFeatures: ["Finesse", "Light"],
        image: null),
    const ArmsData(
        name: 'Shortsword',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 10),
        damage: Dice.d6,
        damageType: DamageTypes.piercing,
        weight: 2,
        armsFeatures: ["Finesse", "Light"],
        image: null),
    const ArmsData(
        name: 'Trident',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 5),
        damage: Dice.d6,
        damageType: DamageTypes.piercing,
        weight: 4,
        armsFeatures: ["Thrown", "Versatile"],
        image: null),
    const ArmsData(
        name: 'War pick',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 5),
        damage: Dice.d8,
        damageType: DamageTypes.piercing,
        weight: 2,
        armsFeatures: [],
        image: null),
    const ArmsData(
        name: 'Warhammer',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 15),
        damage: Dice.d8,
        damageType: DamageTypes.bludgeoning,
        weight: 2,
        armsFeatures: ["Versatile"],
        image: null),
    const ArmsData(
        name: 'Whip',
        isSimple: false,
        isMelee: true,
        price: CoinsData(golden: 2),
        damage: Dice.d4,
        damageType: DamageTypes.slashing,
        weight: 3,
        armsFeatures: ["Finesse", "Reach"],
        image: null),
    const ArmsData(
        name: 'Crossbow, hand',
        isSimple: false,
        isMelee: false,
        price: CoinsData(golden: 75),
        damage: Dice.d6,
        damageType: DamageTypes.piercing,
        weight: 3,
        armsFeatures: ["Ammunition", "Light", "Loading"],
        image: null),
    const ArmsData(
        name: 'Crossbow, heavy',
        isSimple: false,
        isMelee: false,
        price: CoinsData(golden: 50),
        damage: Dice.d10,
        damageType: DamageTypes.piercing,
        weight: 18,
        armsFeatures: ["Ammunition", "Heavy", "Loading", "Two-handed"],
        image: null),
    const ArmsData(
        name: 'Longbow',
        isSimple: false,
        isMelee: false,
        price: CoinsData(golden: 50),
        damage: Dice.d8,
        damageType: DamageTypes.piercing,
        weight: 2,
        armsFeatures: ["Ammunition", "Heavy", "Two-handed"],
        image: null),
    const ArmsData(
        name: 'Net',
        isSimple: false,
        isMelee: false,
        price: CoinsData(golden: 1),
        damage: null,
        damageType: null,
        weight: 3,
        armsFeatures: ["Special", "Thrown"],
        image: null),
  ];
}
