// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Er_rZIYedq5jOw_3TWr7BnVwFE5IqVY',
    appId: '1:569634408498:web:0520d5b38591aec654942b',
    messagingSenderId: '569634408498',
    projectId: 'dnd-helper-app-guap-project',
    authDomain: 'dnd-helper-app-guap-project.firebaseapp.com',
    storageBucket: 'dnd-helper-app-guap-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdBgJxxgoWBP2hRTBaQTvkFKmUiTJ_qmA',
    appId: '1:569634408498:android:0c70c3056b18a08f54942b',
    messagingSenderId: '569634408498',
    projectId: 'dnd-helper-app-guap-project',
    storageBucket: 'dnd-helper-app-guap-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjxndPNAGovjBqrpu32_Fu9l_OpxpkJQ4',
    appId: '1:569634408498:ios:87174d40fc4dc2db54942b',
    messagingSenderId: '569634408498',
    projectId: 'dnd-helper-app-guap-project',
    storageBucket: 'dnd-helper-app-guap-project.firebasestorage.app',
    iosBundleId: 'com.example.dndHelperFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjxndPNAGovjBqrpu32_Fu9l_OpxpkJQ4',
    appId: '1:569634408498:ios:87174d40fc4dc2db54942b',
    messagingSenderId: '569634408498',
    projectId: 'dnd-helper-app-guap-project',
    storageBucket: 'dnd-helper-app-guap-project.firebasestorage.app',
    iosBundleId: 'com.example.dndHelperFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Er_rZIYedq5jOw_3TWr7BnVwFE5IqVY',
    appId: '1:569634408498:web:1f63eb98c85418e854942b',
    messagingSenderId: '569634408498',
    projectId: 'dnd-helper-app-guap-project',
    authDomain: 'dnd-helper-app-guap-project.firebaseapp.com',
    storageBucket: 'dnd-helper-app-guap-project.firebasestorage.app',
  );
}
