using dnd_helper_backend.Core.Models;
using dnd_helper_backend.Core.ValueObjects;
using System.Threading.Tasks;

namespace dnd_helper_backend.Application.Services
{
    public interface ICharacterService
    {
        Task<List<Character>> GetAllCharacters();
        Task<Character> GetById(Guid characterId);
        Task<Guid> DeleteCharacter(Guid characterId);
        Task<List<Character>> GetByUserId(Guid userId);

        Task<Guid> CreateCharacter(Guid userId,
        string? characterName = null,
        Race? characterRace = null,
        SubRace? subrace = null,
        Class? characterClass = null,
        SubClass? subclass = null,
        Background? background = null,
        int experience = 0,
        string? diceHit = null,
        int? maxHitPoints = null,
        int? currentHitPoints = null,
        int? temporaryHitPoints = null,
        int? speed = null,
        int? armorClass = null,
        bool inspiration = false,
        string? conditions = null,
        int? exhaustion = null,
        Dictionary<string, int>? attributes = null,
        string?[]? savingThrows = null,
        string?[]? skillsProficiency = null,
        string?[]? skillsExpertise = null,
        Arms[]? attacks = null,
        Spell[]? preparedSpells = null,
        Spell[]? knownSpells = null,
        string? spellcastingAttribute = null,
        Dictionary<int, int>? spellSlots = null,
        string?[]? languages = null,
        string?[]? tools = null,
        string?[]? weapons = null,
        string? ideology = null,
        string? biography = null,
        string? weight = null,
        string? height = null,
        string? age = null,
        string? hairColor = null,
        string? eyeColor = null,
        string? skinColor = null,
        string? alliesAndOrganizations = null,
        string? purpose = null,
        string? ideals = null,
        string? bonds = null,
        string? flaws = null,
        string? notes = null,
        Coins? coins = null,
        string?[]? equipment = null,
        string?[]? treasures = null);
        Task<Guid> UpdateCharacter(Guid id, Guid userId,
                                        string? characterName = null,
                                        Race? characterRace = null,
                                        SubRace? subrace = null,
                                        Class? characterClass = null,
                                        SubClass? subclass = null,
                                        Background? background = null,
                                        int experience = 0,
                                        string? diceHit = null,
                                        int? maxHitPoints = null,
                                        int? currentHitPoints = null,
                                        int? temporaryHitPoints = null,
                                        int? speed = null,
                                        int? armorClass = null,
                                        bool inspiration = false,
                                        string? conditions = null,
                                        int? exhaustion = null,
                                        Dictionary<string, int>? attributes = null,
                                        string?[]? savingThrows = null,
                                        string?[]? skillsProficiency = null,
                                        string?[]? skillsExpertise = null,
                                        Arms[]? attacks = null,
                                        Spell[]? preparedSpells = null,
                                        Spell[]? knownSpells = null,
                                        string? spellcastingAttribute = null,
                                        Dictionary<int, int>? spellSlots = null,
                                        string?[]? languages = null,
                                        string?[]? tools = null,
                                        string?[]? weapons = null,
                                        string? ideology = null,
                                        string? biography = null,
                                        string? weight = null,
                                        string? height = null,
                                        string? age = null,
                                        string? hairColor = null,
                                        string? eyeColor = null,
                                        string? skinColor = null,
                                        string? alliesAndOrganizations = null,
                                        string? purpose = null,
                                        string? ideals = null,
                                        string? bonds = null,
                                        string? flaws = null,
                                        string? notes = null,
                                        Coins? coins = null,
                                        string?[]? equipment = null,
                                        string?[]? treasures = null);
    }
}