name: dnd_helper_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  build_runner: ^2.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.0
  freezed: ^2.0.0
  json_serializable: ^6.0.0
flutter:
  uses-material-design: true
