name: dnd_helper_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  go_router: ^10.1.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  path:
  adaptive_breakpoints: ^0.1.7
  flutter_layout_grid: ^2.0.7
  http: ^1.2.2
  encrypt_shared_preferences: ^0.8.1
  gap: ^3.0.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_lints: '>=3.0.0 <5.0.0'
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  json_serializable:
  riverpod_lint: ^2.3.10
  sizer: ^3.0.3
  
flutter:
  uses-material-design: true
  assets:
  - assets/icons/class_icons/
  - assets/jsons/
  - assets/icons/
  - assets/icons/2x/
  - assets/icons/3x/